run:
  timeout: 5m
linters:
  enable-all: true
  disable:
    - depguard
    - err113
    - exhaustruct
    - testpackage
    - tagliatelle
    - go

linters-settings:
  lll:
    line-length: 180
  misspell:
    locale: UK
    ignore-words:
      - "teh"
  tagalign:
    order:
      - "short"
      - "long"
      - "description"
      - "env"
      - "required"
      - "default"
      - "choices"